language: python
sudo: false
dist: trusty

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1
    - python: 3.6
      env: CHECK_TYPING=1
    - language: generic
      env: USE_PYPY_NIGHTLY=1
    - python: 3.6
    # As of 2018-07-05, Travis's 3.7 and 3.8 builds only work if you
    # use dist: xenial AND sudo: required
    # See: https://github.com/python-trio/trio/pull/556#issuecomment-402879391
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.8-dev
      dist: xenial
      sudo: required
    - os: osx
      language: generic
      env: MACPYTHON=3.6.6
    - os: osx
      language: generic
      env: MACPYTHON=3.7.0

script:
  - ci/travis.sh
