language: python
dist: xenial

matrix:
  include:
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_LINT=1
    # The pypy tests are slow, so we list them first
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    - python: 3.6
    - python: 3.7
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
