language: python
dist: xenial

matrix:
  include:
    # The pypy tests are slow, so we list them first
    - python: pypy3.6-7.2.0
      dist: bionic
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev

    # Disabled because we can't build typed-ast
    #- python: 3.9-dev

    # Temporarily disabled during the high-churn period of 3.10
    # E.g.: https://github.com/MagicStack/immutables/issues/46
    #- python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
